// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.roda;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import ro.roda.AclObjectIdentityDataOnDemand;
import ro.roda.AclObjectIdentityIntegrationTest;
import ro.roda.service.AclObjectIdentityService;

privileged aspect AclObjectIdentityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AclObjectIdentityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AclObjectIdentityIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AclObjectIdentityIntegrationTest: @Transactional;
    
    @Autowired
    AclObjectIdentityDataOnDemand AclObjectIdentityIntegrationTest.dod;
    
    @Autowired
    AclObjectIdentityService AclObjectIdentityIntegrationTest.aclObjectIdentityService;
    
    @Test
    public void AclObjectIdentityIntegrationTest.testCountAllAclObjectIdentitys() {
        Assert.assertNotNull("Data on demand for 'AclObjectIdentity' failed to initialize correctly", dod.getRandomAclObjectIdentity());
        long count = aclObjectIdentityService.countAllAclObjectIdentitys();
        Assert.assertTrue("Counter for 'AclObjectIdentity' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AclObjectIdentityIntegrationTest.testFindAclObjectIdentity() {
        AclObjectIdentity obj = dod.getRandomAclObjectIdentity();
        Assert.assertNotNull("Data on demand for 'AclObjectIdentity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AclObjectIdentity' failed to provide an identifier", id);
        obj = aclObjectIdentityService.findAclObjectIdentity(id);
        Assert.assertNotNull("Find method for 'AclObjectIdentity' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AclObjectIdentity' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AclObjectIdentityIntegrationTest.testFindAllAclObjectIdentitys() {
        Assert.assertNotNull("Data on demand for 'AclObjectIdentity' failed to initialize correctly", dod.getRandomAclObjectIdentity());
        long count = aclObjectIdentityService.countAllAclObjectIdentitys();
        Assert.assertTrue("Too expensive to perform a find all test for 'AclObjectIdentity', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AclObjectIdentity> result = aclObjectIdentityService.findAllAclObjectIdentitys();
        Assert.assertNotNull("Find all method for 'AclObjectIdentity' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AclObjectIdentity' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AclObjectIdentityIntegrationTest.testFindAclObjectIdentityEntries() {
        Assert.assertNotNull("Data on demand for 'AclObjectIdentity' failed to initialize correctly", dod.getRandomAclObjectIdentity());
        long count = aclObjectIdentityService.countAllAclObjectIdentitys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AclObjectIdentity> result = aclObjectIdentityService.findAclObjectIdentityEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AclObjectIdentity' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AclObjectIdentity' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AclObjectIdentityIntegrationTest.testSaveAclObjectIdentity() {
        Assert.assertNotNull("Data on demand for 'AclObjectIdentity' failed to initialize correctly", dod.getRandomAclObjectIdentity());
        AclObjectIdentity obj = dod.getNewTransientAclObjectIdentity(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AclObjectIdentity' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AclObjectIdentity' identifier to be null", obj.getId());
        aclObjectIdentityService.saveAclObjectIdentity(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'AclObjectIdentity' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AclObjectIdentityIntegrationTest.testDeleteAclObjectIdentity() {
        AclObjectIdentity obj = dod.getRandomAclObjectIdentity();
        Assert.assertNotNull("Data on demand for 'AclObjectIdentity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AclObjectIdentity' failed to provide an identifier", id);
        obj = aclObjectIdentityService.findAclObjectIdentity(id);
        aclObjectIdentityService.deleteAclObjectIdentity(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'AclObjectIdentity' with identifier '" + id + "'", aclObjectIdentityService.findAclObjectIdentity(id));
    }
    
}
