// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.roda;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ro.roda.Catalog;
import ro.roda.CatalogDataOnDemand;
import ro.roda.Rodauser;
import ro.roda.RodauserDataOnDemand;
import ro.roda.service.CatalogService;

privileged aspect CatalogDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CatalogDataOnDemand: @Component;
    
    private Random CatalogDataOnDemand.rnd = new SecureRandom();
    
    private List<Catalog> CatalogDataOnDemand.data;
    
    @Autowired
    RodauserDataOnDemand CatalogDataOnDemand.rodauserDataOnDemand;
    
    @Autowired
    CatalogService CatalogDataOnDemand.catalogService;
    
    public Catalog CatalogDataOnDemand.getNewTransientCatalog(int index) {
        Catalog obj = new Catalog();
        setAdded(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        setOwner(obj, index);
        setParentId(obj, index);
        setSequencenr(obj, index);
        return obj;
    }
    
    public void CatalogDataOnDemand.setAdded(Catalog obj, int index) {
        Calendar added = Calendar.getInstance();
        obj.setAdded(added);
    }
    
    public void CatalogDataOnDemand.setDescription(Catalog obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void CatalogDataOnDemand.setName(Catalog obj, int index) {
        String name = "name_" + index;
        if (name.length() > 200) {
            name = name.substring(0, 200);
        }
        obj.setName(name);
    }
    
    public void CatalogDataOnDemand.setOwner(Catalog obj, int index) {
        Rodauser owner = rodauserDataOnDemand.getRandomRodauser();
        obj.setOwner(owner);
    }
    
    public void CatalogDataOnDemand.setParentId(Catalog obj, int index) {
        Integer parentId = new Integer(index);
        obj.setParentId(parentId);
    }
    
    public void CatalogDataOnDemand.setSequencenr(Catalog obj, int index) {
        Integer sequencenr = new Integer(index);
        obj.setSequencenr(sequencenr);
    }
    
    public Catalog CatalogDataOnDemand.getSpecificCatalog(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Catalog obj = data.get(index);
        Integer id = obj.getId();
        return catalogService.findCatalog(id);
    }
    
    public Catalog CatalogDataOnDemand.getRandomCatalog() {
        init();
        Catalog obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return catalogService.findCatalog(id);
    }
    
    public boolean CatalogDataOnDemand.modifyCatalog(Catalog obj) {
        return false;
    }
    
    public void CatalogDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = catalogService.findCatalogEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Catalog' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Catalog>();
        for (int i = 0; i < 10; i++) {
            Catalog obj = getNewTransientCatalog(i);
            try {
                catalogService.saveCatalog(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
