// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.roda;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import ro.roda.CmsFile;
import ro.roda.CmsFileIntegrationTest;

privileged aspect CmsFileIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CmsFileIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CmsFileIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CmsFileIntegrationTest: @Transactional;
    
    @Test
    public void CmsFileIntegrationTest.testCountCmsFiles() {
        Assert.assertNotNull("Data on demand for 'CmsFile' failed to initialize correctly", dod.getRandomCmsFile());
        long count = CmsFile.countCmsFiles();
        Assert.assertTrue("Counter for 'CmsFile' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CmsFileIntegrationTest.testFindCmsFile() {
        CmsFile obj = dod.getRandomCmsFile();
        Assert.assertNotNull("Data on demand for 'CmsFile' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CmsFile' failed to provide an identifier", id);
        obj = CmsFile.findCmsFile(id);
        Assert.assertNotNull("Find method for 'CmsFile' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CmsFile' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CmsFileIntegrationTest.testFindAllCmsFiles() {
        Assert.assertNotNull("Data on demand for 'CmsFile' failed to initialize correctly", dod.getRandomCmsFile());
        long count = CmsFile.countCmsFiles();
        Assert.assertTrue("Too expensive to perform a find all test for 'CmsFile', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CmsFile> result = CmsFile.findAllCmsFiles();
        Assert.assertNotNull("Find all method for 'CmsFile' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CmsFile' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CmsFileIntegrationTest.testFindCmsFileEntries() {
        Assert.assertNotNull("Data on demand for 'CmsFile' failed to initialize correctly", dod.getRandomCmsFile());
        long count = CmsFile.countCmsFiles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CmsFile> result = CmsFile.findCmsFileEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CmsFile' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CmsFile' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CmsFileIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CmsFile' failed to initialize correctly", dod.getRandomCmsFile());
        CmsFile obj = dod.getNewTransientCmsFile(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CmsFile' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CmsFile' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'CmsFile' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CmsFileIntegrationTest.testRemove() {
        CmsFile obj = dod.getRandomCmsFile();
        Assert.assertNotNull("Data on demand for 'CmsFile' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CmsFile' failed to provide an identifier", id);
        obj = CmsFile.findCmsFile(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CmsFile' with identifier '" + id + "'", CmsFile.findCmsFile(id));
    }
    
}
