// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.roda;

import org.springframework.beans.factory.annotation.Configurable;
import ro.roda.CmsFolderDataOnDemand;

privileged aspect CmsFolderDataOnDemand_Roo_Configurable {
    
    declare @type: CmsFolderDataOnDemand: @Configurable;
    
}
