// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.roda;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ro.roda.Form;
import ro.roda.FormDataOnDemand;
import ro.roda.FormEditedTextVar;
import ro.roda.FormEditedTextVarDataOnDemand;
import ro.roda.FormEditedTextVarPK;
import ro.roda.Variable;
import ro.roda.VariableDataOnDemand;
import ro.roda.service.FormEditedTextVarService;

privileged aspect FormEditedTextVarDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FormEditedTextVarDataOnDemand: @Component;
    
    private Random FormEditedTextVarDataOnDemand.rnd = new SecureRandom();
    
    private List<FormEditedTextVar> FormEditedTextVarDataOnDemand.data;
    
    @Autowired
    FormDataOnDemand FormEditedTextVarDataOnDemand.formDataOnDemand;
    
    @Autowired
    VariableDataOnDemand FormEditedTextVarDataOnDemand.variableDataOnDemand;
    
    @Autowired
    FormEditedTextVarService FormEditedTextVarDataOnDemand.formEditedTextVarService;
    
    public FormEditedTextVar FormEditedTextVarDataOnDemand.getNewTransientFormEditedTextVar(int index) {
        FormEditedTextVar obj = new FormEditedTextVar();
        setEmbeddedIdClass(obj, index);
        setFormId(obj, index);
        setText(obj, index);
        setVariableId(obj, index);
        return obj;
    }
    
    public void FormEditedTextVarDataOnDemand.setEmbeddedIdClass(FormEditedTextVar obj, int index) {
        Long variableId = new Integer(index).longValue();
        Long formId = new Integer(index).longValue();
        
        FormEditedTextVarPK embeddedIdClass = new FormEditedTextVarPK(variableId, formId);
        obj.setId(embeddedIdClass);
    }
    
    public void FormEditedTextVarDataOnDemand.setFormId(FormEditedTextVar obj, int index) {
        Form formId = formDataOnDemand.getRandomForm();
        obj.setFormId(formId);
    }
    
    public void FormEditedTextVarDataOnDemand.setText(FormEditedTextVar obj, int index) {
        String text = "text_" + index;
        obj.setText(text);
    }
    
    public void FormEditedTextVarDataOnDemand.setVariableId(FormEditedTextVar obj, int index) {
        Variable variableId = variableDataOnDemand.getRandomVariable();
        obj.setVariableId(variableId);
    }
    
    public FormEditedTextVar FormEditedTextVarDataOnDemand.getSpecificFormEditedTextVar(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        FormEditedTextVar obj = data.get(index);
        FormEditedTextVarPK id = obj.getId();
        return formEditedTextVarService.findFormEditedTextVar(id);
    }
    
    public FormEditedTextVar FormEditedTextVarDataOnDemand.getRandomFormEditedTextVar() {
        init();
        FormEditedTextVar obj = data.get(rnd.nextInt(data.size()));
        FormEditedTextVarPK id = obj.getId();
        return formEditedTextVarService.findFormEditedTextVar(id);
    }
    
    public boolean FormEditedTextVarDataOnDemand.modifyFormEditedTextVar(FormEditedTextVar obj) {
        return false;
    }
    
    public void FormEditedTextVarDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = formEditedTextVarService.findFormEditedTextVarEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'FormEditedTextVar' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<FormEditedTextVar>();
        for (int i = 0; i < 10; i++) {
            FormEditedTextVar obj = getNewTransientFormEditedTextVar(i);
            try {
                formEditedTextVarService.saveFormEditedTextVar(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
