// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.roda;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ro.roda.InstancePersonAssoc;
import ro.roda.InstancePersonAssocDataOnDemand;
import ro.roda.service.InstancePersonAssocService;

privileged aspect InstancePersonAssocDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InstancePersonAssocDataOnDemand: @Component;
    
    private Random InstancePersonAssocDataOnDemand.rnd = new SecureRandom();
    
    private List<InstancePersonAssoc> InstancePersonAssocDataOnDemand.data;
    
    @Autowired
    InstancePersonAssocService InstancePersonAssocDataOnDemand.instancePersonAssocService;
    
    public InstancePersonAssoc InstancePersonAssocDataOnDemand.getNewTransientInstancePersonAssoc(int index) {
        InstancePersonAssoc obj = new InstancePersonAssoc();
        setAssocDescription(obj, index);
        setAssocName(obj, index);
        return obj;
    }
    
    public void InstancePersonAssocDataOnDemand.setAssocDescription(InstancePersonAssoc obj, int index) {
        String assocDescription = "assocDescription_" + index;
        obj.setAssocDescription(assocDescription);
    }
    
    public void InstancePersonAssocDataOnDemand.setAssocName(InstancePersonAssoc obj, int index) {
        String assocName = "assocName_" + index;
        if (assocName.length() > 100) {
            assocName = assocName.substring(0, 100);
        }
        obj.setAssocName(assocName);
    }
    
    public InstancePersonAssoc InstancePersonAssocDataOnDemand.getSpecificInstancePersonAssoc(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        InstancePersonAssoc obj = data.get(index);
        Integer id = obj.getId();
        return instancePersonAssocService.findInstancePersonAssoc(id);
    }
    
    public InstancePersonAssoc InstancePersonAssocDataOnDemand.getRandomInstancePersonAssoc() {
        init();
        InstancePersonAssoc obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return instancePersonAssocService.findInstancePersonAssoc(id);
    }
    
    public boolean InstancePersonAssocDataOnDemand.modifyInstancePersonAssoc(InstancePersonAssoc obj) {
        return false;
    }
    
    public void InstancePersonAssocDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = instancePersonAssocService.findInstancePersonAssocEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'InstancePersonAssoc' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<InstancePersonAssoc>();
        for (int i = 0; i < 10; i++) {
            InstancePersonAssoc obj = getNewTransientInstancePersonAssoc(i);
            try {
                instancePersonAssocService.saveInstancePersonAssoc(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
