// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.roda;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import ro.roda.StudyOrg;
import ro.roda.StudyOrgDataOnDemand;
import ro.roda.StudyOrgIntegrationTest;
import ro.roda.StudyOrgPK;

privileged aspect StudyOrgIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StudyOrgIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StudyOrgIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StudyOrgIntegrationTest: @Transactional;
    
    @Autowired
    private StudyOrgDataOnDemand StudyOrgIntegrationTest.dod;
    
    @Test
    public void StudyOrgIntegrationTest.testCountStudyOrgs() {
        Assert.assertNotNull("Data on demand for 'StudyOrg' failed to initialize correctly", dod.getRandomStudyOrg());
        long count = StudyOrg.countStudyOrgs();
        Assert.assertTrue("Counter for 'StudyOrg' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StudyOrgIntegrationTest.testFindStudyOrg() {
        StudyOrg obj = dod.getRandomStudyOrg();
        Assert.assertNotNull("Data on demand for 'StudyOrg' failed to initialize correctly", obj);
        StudyOrgPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudyOrg' failed to provide an identifier", id);
        obj = StudyOrg.findStudyOrg(id);
        Assert.assertNotNull("Find method for 'StudyOrg' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StudyOrg' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StudyOrgIntegrationTest.testFindAllStudyOrgs() {
        Assert.assertNotNull("Data on demand for 'StudyOrg' failed to initialize correctly", dod.getRandomStudyOrg());
        long count = StudyOrg.countStudyOrgs();
        Assert.assertTrue("Too expensive to perform a find all test for 'StudyOrg', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StudyOrg> result = StudyOrg.findAllStudyOrgs();
        Assert.assertNotNull("Find all method for 'StudyOrg' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StudyOrg' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StudyOrgIntegrationTest.testFindStudyOrgEntries() {
        Assert.assertNotNull("Data on demand for 'StudyOrg' failed to initialize correctly", dod.getRandomStudyOrg());
        long count = StudyOrg.countStudyOrgs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StudyOrg> result = StudyOrg.findStudyOrgEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StudyOrg' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StudyOrg' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StudyOrgIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StudyOrg' failed to initialize correctly", dod.getRandomStudyOrg());
        StudyOrg obj = dod.getNewTransientStudyOrg(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StudyOrg' failed to provide a new transient entity", obj);
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'StudyOrg' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StudyOrgIntegrationTest.testRemove() {
        StudyOrg obj = dod.getRandomStudyOrg();
        Assert.assertNotNull("Data on demand for 'StudyOrg' failed to initialize correctly", obj);
        StudyOrgPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudyOrg' failed to provide an identifier", id);
        obj = StudyOrg.findStudyOrg(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StudyOrg' with identifier '" + id + "'", StudyOrg.findStudyOrg(id));
    }
    
}
