// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.roda;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import ro.roda.UnitAnalysis;
import ro.roda.UnitAnalysisDataOnDemand;
import ro.roda.UnitAnalysisIntegrationTest;

privileged aspect UnitAnalysisIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UnitAnalysisIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UnitAnalysisIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UnitAnalysisIntegrationTest: @Transactional;
    
    @Autowired
    private UnitAnalysisDataOnDemand UnitAnalysisIntegrationTest.dod;
    
    @Test
    public void UnitAnalysisIntegrationTest.testCountUnitAnalyses() {
        Assert.assertNotNull("Data on demand for 'UnitAnalysis' failed to initialize correctly", dod.getRandomUnitAnalysis());
        long count = UnitAnalysis.countUnitAnalyses();
        Assert.assertTrue("Counter for 'UnitAnalysis' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UnitAnalysisIntegrationTest.testFindUnitAnalysis() {
        UnitAnalysis obj = dod.getRandomUnitAnalysis();
        Assert.assertNotNull("Data on demand for 'UnitAnalysis' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UnitAnalysis' failed to provide an identifier", id);
        obj = UnitAnalysis.findUnitAnalysis(id);
        Assert.assertNotNull("Find method for 'UnitAnalysis' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UnitAnalysis' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UnitAnalysisIntegrationTest.testFindAllUnitAnalyses() {
        Assert.assertNotNull("Data on demand for 'UnitAnalysis' failed to initialize correctly", dod.getRandomUnitAnalysis());
        long count = UnitAnalysis.countUnitAnalyses();
        Assert.assertTrue("Too expensive to perform a find all test for 'UnitAnalysis', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UnitAnalysis> result = UnitAnalysis.findAllUnitAnalyses();
        Assert.assertNotNull("Find all method for 'UnitAnalysis' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UnitAnalysis' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UnitAnalysisIntegrationTest.testFindUnitAnalysisEntries() {
        Assert.assertNotNull("Data on demand for 'UnitAnalysis' failed to initialize correctly", dod.getRandomUnitAnalysis());
        long count = UnitAnalysis.countUnitAnalyses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UnitAnalysis> result = UnitAnalysis.findUnitAnalysisEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UnitAnalysis' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UnitAnalysis' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UnitAnalysisIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UnitAnalysis' failed to initialize correctly", dod.getRandomUnitAnalysis());
        UnitAnalysis obj = dod.getNewTransientUnitAnalysis(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UnitAnalysis' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UnitAnalysis' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UnitAnalysis' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UnitAnalysisIntegrationTest.testRemove() {
        UnitAnalysis obj = dod.getRandomUnitAnalysis();
        Assert.assertNotNull("Data on demand for 'UnitAnalysis' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UnitAnalysis' failed to provide an identifier", id);
        obj = UnitAnalysis.findUnitAnalysis(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UnitAnalysis' with identifier '" + id + "'", UnitAnalysis.findUnitAnalysis(id));
    }
    
}
