// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.roda;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ro.roda.UserSettingGroup;
import ro.roda.UserSettingGroupDataOnDemand;
import ro.roda.service.UserSettingGroupService;

privileged aspect UserSettingGroupDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserSettingGroupDataOnDemand: @Component;
    
    private Random UserSettingGroupDataOnDemand.rnd = new SecureRandom();
    
    private List<UserSettingGroup> UserSettingGroupDataOnDemand.data;
    
    @Autowired
    UserSettingGroupService UserSettingGroupDataOnDemand.userSettingGroupService;
    
    public UserSettingGroup UserSettingGroupDataOnDemand.getNewTransientUserSettingGroup(int index) {
        UserSettingGroup obj = new UserSettingGroup();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void UserSettingGroupDataOnDemand.setDescription(UserSettingGroup obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void UserSettingGroupDataOnDemand.setName(UserSettingGroup obj, int index) {
        String name = "name_" + index;
        if (name.length() > 100) {
            name = name.substring(0, 100);
        }
        obj.setName(name);
    }
    
    public UserSettingGroup UserSettingGroupDataOnDemand.getSpecificUserSettingGroup(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserSettingGroup obj = data.get(index);
        Integer id = obj.getId();
        return userSettingGroupService.findUserSettingGroup(id);
    }
    
    public UserSettingGroup UserSettingGroupDataOnDemand.getRandomUserSettingGroup() {
        init();
        UserSettingGroup obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return userSettingGroupService.findUserSettingGroup(id);
    }
    
    public boolean UserSettingGroupDataOnDemand.modifyUserSettingGroup(UserSettingGroup obj) {
        return false;
    }
    
    public void UserSettingGroupDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = userSettingGroupService.findUserSettingGroupEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserSettingGroup' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserSettingGroup>();
        for (int i = 0; i < 10; i++) {
            UserSettingGroup obj = getNewTransientUserSettingGroup(i);
            try {
                userSettingGroupService.saveUserSettingGroup(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
