// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.roda.domain;

import java.io.Serializable;
import ro.roda.domain.FormSelectionVarPK;

privileged aspect FormSelectionVarPK_Roo_Serializable {
    
    declare parents: FormSelectionVarPK implements Serializable;
    
    private static final long FormSelectionVarPK.serialVersionUID = 1L;
    
}
