// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.roda;

import java.io.Serializable;
import ro.roda.SelectionVariableItemPK;

privileged aspect SelectionVariableItemPK_Roo_Serializable {
    
    declare parents: SelectionVariableItemPK implements Serializable;
    
    private static final long SelectionVariableItemPK.serialVersionUID = 1L;
    
}
