SELECT me.id, me.name FROM lang me WHERE ( me.id =  'ro' );
INSERT INTO lang ( id, name) VALUES (  'ro',  'română' );
SELECT me.id, me.name FROM lang me WHERE ( me.id =  'en' );
INSERT INTO lang ( id, name) VALUES (  'en',  'english' );
SELECT me.id, me.name FROM lang me WHERE ( me.id =  'fr' );
INSERT INTO lang ( id, name) VALUES (  'fr',  'français' );
SELECT me.id, me.name FROM lang me WHERE ( me.id =  'fi' );
INSERT INTO lang ( id, name) VALUES (  'fi',  'suomi' );
SELECT me.id, me.name FROM lang me WHERE ( me.id =  'de' );
INSERT INTO lang ( id, name) VALUES (  'de',  'deutsch' );
SELECT me.id, me.name FROM lang me WHERE ( me.id =  'he' );
INSERT INTO lang ( id, name) VALUES (  'he',  'עברית' );
SELECT me.id, me.name FROM lang me WHERE ( me.id =  'hu' );
INSERT INTO lang ( id, name) VALUES (  'hu',  'magyar' );
SELECT me.id, me.name FROM lang me WHERE ( me.id =  'it' );
INSERT INTO lang ( id, name) VALUES (  'it',  'italiano' );
SELECT me.id, me.name FROM lang me WHERE ( me.id =  'lv' );
INSERT INTO lang ( id, name) VALUES (  'lv',  'latviešu' );
SELECT me.id, me.name FROM lang me WHERE ( me.id =  'pl' );
INSERT INTO lang ( id, name) VALUES (  'pl',  'polszczyzna' );
SELECT me.id, me.name FROM lang me WHERE ( me.id =  'pt' );
INSERT INTO lang ( id, name) VALUES (  'pt',  'português' );
SELECT me.id, me.name FROM lang me WHERE ( me.id =  'ru' );
INSERT INTO lang ( id, name) VALUES (  'ru',  'русский' );
SELECT me.id, me.name FROM lang me WHERE ( me.id =  'sk' );
INSERT INTO lang ( id, name) VALUES (  'sk',  'slovenčina' );
SELECT me.id, me.name FROM prefix me WHERE ( me.id =  '1' );
INSERT INTO prefix ( id, name) VALUES (  '1',  'domnul' );
SELECT me.id, me.name FROM prefix me WHERE ( me.id =  '2' );
INSERT INTO prefix ( id, name) VALUES (  '2',  'doamna' );
SELECT me.id, me.name FROM prefix me WHERE ( me.id =  '3' );
INSERT INTO prefix ( id, name) VALUES (  '3',  'domnişoara' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'ro' );
INSERT INTO country ( alpha3, id, name) VALUES (  'rou',  'ro',  'românia' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'at' );
INSERT INTO country ( alpha3, id, name) VALUES (  'aut',  'at',  'austria' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'be' );
INSERT INTO country ( alpha3, id, name) VALUES (  'bel',  'be',  'belgia' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'bg' );
INSERT INTO country ( alpha3, id, name) VALUES (  'bgr',  'bg',  'bulgaria' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'cy' );
INSERT INTO country ( alpha3, id, name) VALUES (  'cyp',  'cy',  'cyprus' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'cz' );
INSERT INTO country ( alpha3, id, name) VALUES (  'cze',  'cz',  'cehia' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'dk' );
INSERT INTO country ( alpha3, id, name) VALUES (  'dnk',  'dk',  'danemarca' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'ee' );
INSERT INTO country ( alpha3, id, name) VALUES (  'est',  'ee',  'estonia' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'fi' );
INSERT INTO country ( alpha3, id, name) VALUES (  'fin',  'fi',  'finlanda' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'fr' );
INSERT INTO country ( alpha3, id, name) VALUES (  'fra',  'fr',  'franţa' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'de' );
INSERT INTO country ( alpha3, id, name) VALUES (  'deu',  'de',  'germania' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'gr' );
INSERT INTO country ( alpha3, id, name) VALUES (  'grc',  'gr',  'grecia' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'hu' );
INSERT INTO country ( alpha3, id, name) VALUES (  'hun',  'hu',  'ungaria' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'ie' );
INSERT INTO country ( alpha3, id, name) VALUES (  'irl',  'ie',  'irlanda' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'it' );
INSERT INTO country ( alpha3, id, name) VALUES (  'ita',  'it',  'italia' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'lv' );
INSERT INTO country ( alpha3, id, name) VALUES (  'lva',  'lv',  'letonia' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'lt' );
INSERT INTO country ( alpha3, id, name) VALUES (  'ltu',  'lt',  'lituania' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'lu' );
INSERT INTO country ( alpha3, id, name) VALUES (  'lux',  'lu',  'luxemburg' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'mt' );
INSERT INTO country ( alpha3, id, name) VALUES (  'mlt',  'mt',  'malta' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'nl' );
INSERT INTO country ( alpha3, id, name) VALUES (  'nld',  'nl',  'olanda' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'pl' );
INSERT INTO country ( alpha3, id, name) VALUES (  'pol',  'pl',  'polonia' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'pt' );
INSERT INTO country ( alpha3, id, name) VALUES (  'prt',  'pt',  'portugalia' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'sk' );
INSERT INTO country ( alpha3, id, name) VALUES (  'svk',  'sk',  'slovacia' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'si' );
INSERT INTO country ( alpha3, id, name) VALUES (  'svn',  'si',  'slovenia' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'es' );
INSERT INTO country ( alpha3, id, name) VALUES (  'esp',  'es',  'spania' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'se' );
INSERT INTO country ( alpha3, id, name) VALUES (  'swe',  'se',  'suedia' );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.id =  'gb' );
INSERT INTO country ( alpha3, id, name) VALUES (  'gbr',  'gb',  'marea britanie' );
SELECT me.id, me.name FROM regiontype me WHERE ( me.name =  'judeţ' );
INSERT INTO regiontype ( name) VALUES (  'judeţ' ) RETURNING id;
SELECT me.id, me.name FROM regiontype me WHERE ( me.name =  'regiune de dezvoltare' );
INSERT INTO regiontype ( name) VALUES (  'regiune de dezvoltare' ) RETURNING id;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'alba' AND me.region_code =  '10' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'alba' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'alba' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'alba',  '10',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'arad' AND me.region_code =  '29' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'arad' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'arad' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'arad',  '29',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'argeş' AND me.region_code =  '38' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'argeş' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'argeş' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'argeş',  '38',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'bacãu' AND me.region_code =  '47' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bacãu' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bacãu' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'bacãu',  '47',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'bihor' AND me.region_code =  '56' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bihor' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bihor' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'bihor',  '56',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'bistriţa-nãsãud' AND me.region_code =  '65' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'bistriţa-nãsãud',  '65',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'botoşani' AND me.region_code =  '74' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'botoşani' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'botoşani' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'botoşani',  '74',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'braşov' AND me.region_code =  '83' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'braşov' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'braşov' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'braşov',  '83',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'brãila' AND me.region_code =  '92' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'brãila' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'brãila' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'brãila',  '92',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'buzãu' AND me.region_code =  '109' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'buzãu' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'buzãu' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'buzãu',  '109',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'caraş-severin' AND me.region_code =  '118' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'caraş-severin' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'caraş-severin' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'caraş-severin',  '118',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'cãlãraşi' AND me.region_code =  '519' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'cãlãraşi' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'cãlãraşi' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'cãlãraşi',  '519',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'cluj' AND me.region_code =  '127' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'cluj' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'cluj' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'cluj',  '127',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'constanţa' AND me.region_code =  '136' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'constanţa' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'constanţa' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'constanţa',  '136',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'covasna' AND me.region_code =  '145' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'covasna' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'covasna' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'covasna',  '145',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'dâmboviţa' AND me.region_code =  '154' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'dâmboviţa' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'dâmboviţa' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'dâmboviţa',  '154',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'dolj' AND me.region_code =  '163' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'dolj',  '163',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'galaţi' AND me.region_code =  '172' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'galaţi' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'galaţi' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'galaţi',  '172',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'giurgiu' AND me.region_code =  '528' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'giurgiu' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'giurgiu' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'giurgiu',  '528',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'gorj' AND me.region_code =  '181' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'gorj' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'gorj' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'gorj',  '181',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'harghita' AND me.region_code =  '190' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'harghita' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'harghita' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'harghita',  '190',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'hunedoara' AND me.region_code =  '207' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'hunedoara' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'hunedoara' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'hunedoara',  '207',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'ialomiţa' AND me.region_code =  '216' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'ialomiţa' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'ialomiţa' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'ialomiţa',  '216',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'iaşi' AND me.region_code =  '225' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'iaşi' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'iaşi' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'iaşi',  '225',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'ilfov' AND me.region_code =  '234' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'ilfov' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'ilfov' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'ilfov',  '234',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'maramureş' AND me.region_code =  '243' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'maramureş' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'maramureş' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'maramureş',  '243',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'mehedinţi' AND me.region_code =  '252' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'mehedinţi' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'mehedinţi' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'mehedinţi',  '252',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'mureş' AND me.region_code =  '261' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'mureş' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'mureş' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'mureş',  '261',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'neamţ' AND me.region_code =  '270' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'neamţ' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'neamţ' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'neamţ',  '270',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'olt' AND me.region_code =  '289' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'olt' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'olt' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'olt',  '289',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'prahova' AND me.region_code =  '298' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'prahova' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'prahova' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'prahova',  '298',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'satu mare' AND me.region_code =  '305' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'satu mare' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'satu mare' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'satu mare',  '305',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'sãlaj' AND me.region_code =  '314' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'sãlaj' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'sãlaj' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'sãlaj',  '314',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'sibiu' AND me.region_code =  '323' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'sibiu' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'sibiu' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'sibiu',  '323',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'suceava' AND me.region_code =  '332' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'suceava' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'suceava' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'suceava',  '332',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'teleorman' AND me.region_code =  '341' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'teleorman' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'teleorman' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'teleorman',  '341',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'timiş' AND me.region_code =  '350' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'timiş' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'timiş' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'timiş',  '350',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'tulcea' AND me.region_code =  '369' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'tulcea' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'tulcea' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'tulcea',  '369',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'vaslui' AND me.region_code =  '378' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'vaslui' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'vaslui' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'vaslui',  '378',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'vâlcea' AND me.region_code =  '387' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'vâlcea' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'vâlcea' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'vâlcea',  '387',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'vrancea' AND me.region_code =  '396' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'vrancea' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'vrancea' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'vrancea',  '396',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( me.name =  'bucureşti' AND me.region_code =  '403' ) );
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bucureşti' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bucureşti' ) );
BEGIN WORK;
SELECT me.id, me.name, me.alpha3 FROM country me WHERE ( me.name =  'românia' );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'judeţ' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'bucureşti',  '403',  'siruta',  '1' ) RETURNING id;
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '1017' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'alba iulia' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '1017',  'siruta',  '10',  '1',  'siruta',  'ro',  'alba iulia',  'municipiul' ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'centru' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'centru' ) );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'regiune de dezvoltare' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'centru',  NULL,  NULL,  '2' ) RETURNING id;
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '1' AND me.region_id =  '43' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '1',  '43' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'alba' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'alba' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '1' AND me.region_id =  '1' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '1',  '1' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '403' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'bucureşti' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '403',  'siruta',  '1',  '40',  'siruta',  'ro',  'bucureşti',  'municipiul' ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bucureşti-ilfov' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bucureşti-ilfov' ) );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'regiune de dezvoltare' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'bucureşti-ilfov',  NULL,  NULL,  '2' ) RETURNING id;
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '2' AND me.region_id =  '44' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '2',  '44' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bucureşti' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bucureşti' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '2' AND me.region_id =  '42' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '2',  '42' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '1026' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'alba iulia' ) );
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( country_id =  'ro' AND name =  'alba iulia' ) );
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'centru' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'centru' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '1' AND me.region_id =  '43' ) );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'alba' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'alba' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '1' AND me.region_id =  '1' ) );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '1035' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'bãrãbanţ' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '1035',  'siruta',  '1017',  '10',  'siruta',  'ro',  'bãrãbanţ',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'centru' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'centru' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '3' AND me.region_id =  '43' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '3',  '43' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'alba' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'alba' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '3' AND me.region_id =  '1' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '3',  '1' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '1044' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'miceşti' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '1044',  'siruta',  '1017',  '10',  'siruta',  'ro',  'miceşti',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'centru' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'centru' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '4' AND me.region_id =  '43' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '4',  '43' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'alba' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'alba' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '4' AND me.region_id =  '1' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '4',  '1' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '1053' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'oarda' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '1053',  'siruta',  '1017',  '10',  'siruta',  'ro',  'oarda',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'centru' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'centru' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '5' AND me.region_id =  '43' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '5',  '43' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'alba' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'alba' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '5' AND me.region_id =  '1' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '5',  '1' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '1062' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'pâclişa' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '1062',  'siruta',  '1017',  '10',  'siruta',  'ro',  'pâclişa',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'centru' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'centru' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '6' AND me.region_id =  '43' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '6',  '43' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'alba' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'alba' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '6' AND me.region_id =  '1' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '6',  '1' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34752' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'sãrãţel' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34752',  'siruta',  '34690',  '23',  'siruta',  'ro',  'sãrãţel',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'regiune de dezvoltare' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'nord-vest',  NULL,  NULL,  '2' ) RETURNING id;
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '7' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '7',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '7' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '7',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34761' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'valea mãgheruşului' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34761',  'siruta',  '34690',  '23',  'siruta',  'ro',  'valea mãgheruşului',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '8' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '8',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '8' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '8',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34770' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'şieu-odorhei' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34770',  'siruta',  '65',  '3',  'siruta',  'ro',  'şieu-odorhei',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '9' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '9',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '9' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '9',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34789' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'şieu-odorhei' ) );
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( country_id =  'ro' AND name =  'şieu-odorhei' ) );
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '9' AND me.region_id =  '45' ) );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '9' AND me.region_id =  '6' ) );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34798' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'agrişu de jos' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34798',  'siruta',  '34770',  '23',  'siruta',  'ro',  'agrişu de jos',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '10' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '10',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '10' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '10',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34805' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'agrişu de sus' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34805',  'siruta',  '34770',  '23',  'siruta',  'ro',  'agrişu de sus',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '11' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '11',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '11' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '11',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34814' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'bretea' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34814',  'siruta',  '34770',  '23',  'siruta',  'ro',  'bretea',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '12' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '12',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '12' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '12',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34823' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'coasta' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34823',  'siruta',  '34770',  '23',  'siruta',  'ro',  'coasta',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '13' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '13',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '13' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '13',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34832' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'cristur-şieu' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34832',  'siruta',  '34770',  '23',  'siruta',  'ro',  'cristur-şieu',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '14' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '14',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '14' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '14',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34841' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'şirioara' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34841',  'siruta',  '34770',  '23',  'siruta',  'ro',  'şirioara',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '15' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '15',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '15' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '15',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34850' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'şieuţ' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34850',  'siruta',  '65',  '3',  'siruta',  'ro',  'şieuţ',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '16' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '16',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '16' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '16',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34869' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'şieuţ' ) );
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( country_id =  'ro' AND name =  'şieuţ' ) );
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '16' AND me.region_id =  '45' ) );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '16' AND me.region_id =  '6' ) );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34878' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'lunca' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34878',  'siruta',  '34850',  '23',  'siruta',  'ro',  'lunca',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '17' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '17',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '17' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '17',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34887' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'ruştior' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34887',  'siruta',  '34850',  '23',  'siruta',  'ro',  'ruştior',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '18' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '18',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '18' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '18',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34896' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'sebiş' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34896',  'siruta',  '34850',  '23',  'siruta',  'ro',  'sebiş',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '19' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '19',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '19' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '19',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34903' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'şintereag' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34903',  'siruta',  '65',  '3',  'siruta',  'ro',  'şintereag',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '20' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '20',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '20' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '20',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34912' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'şintereag' ) );
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( country_id =  'ro' AND name =  'şintereag' ) );
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '20' AND me.region_id =  '45' ) );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '20' AND me.region_id =  '6' ) );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34921' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'blãjenii de jos' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34921',  'siruta',  '34903',  '23',  'siruta',  'ro',  'blãjenii de jos',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '21' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '21',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '21' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '21',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34930' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'blãjenii de sus' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34930',  'siruta',  '34903',  '23',  'siruta',  'ro',  'blãjenii de sus',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '22' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '22',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '22' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '22',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34949' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'caila' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34949',  'siruta',  '34903',  '23',  'siruta',  'ro',  'caila',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '23' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '23',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '23' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '23',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34958' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'cociu' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34958',  'siruta',  '34903',  '23',  'siruta',  'ro',  'cociu',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '24' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '24',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '24' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '24',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '34967' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'şieu-sfântu' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '34967',  'siruta',  '34903',  '23',  'siruta',  'ro',  'şieu-sfântu',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '25' AND me.region_id =  '45' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '25',  '45' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'bistriţa-nãsãud' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '25' AND me.region_id =  '6' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '25',  '6' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '73362' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'moţãţei garã' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '73362',  'siruta',  '73335',  '23',  'siruta',  'ro',  'moţãţei garã',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'sud-vest' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'sud-vest' ) );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'regiune de dezvoltare' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'sud-vest',  NULL,  NULL,  '2' ) RETURNING id;
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '26' AND me.region_id =  '46' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '26',  '46' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '26' AND me.region_id =  '17' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '26',  '17' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '73371' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'murgaşi' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '73371',  'siruta',  '163',  '3',  'siruta',  'ro',  'murgaşi',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'sud-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'sud-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '27' AND me.region_id =  '46' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '27',  '46' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '27' AND me.region_id =  '17' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '27',  '17' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '73380' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'balota de jos' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '73380',  'siruta',  '73371',  '22',  'siruta',  'ro',  'balota de jos',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'sud-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'sud-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '28' AND me.region_id =  '46' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '28',  '46' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '28' AND me.region_id =  '17' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '28',  '17' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '73399' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'balota de sus' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '73399',  'siruta',  '73371',  '23',  'siruta',  'ro',  'balota de sus',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'sud-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'sud-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '29' AND me.region_id =  '46' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '29',  '46' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '29' AND me.region_id =  '17' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '29',  '17' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '73406' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'buşteni' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '73406',  'siruta',  '73371',  '23',  'siruta',  'ro',  'buşteni',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'sud-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'sud-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '30' AND me.region_id =  '46' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '30',  '46' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '30' AND me.region_id =  '17' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '30',  '17' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '73415' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'gaia' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '73415',  'siruta',  '73371',  '23',  'siruta',  'ro',  'gaia',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'sud-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'sud-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '31' AND me.region_id =  '46' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '31',  '46' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '31' AND me.region_id =  '17' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '31',  '17' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '73424' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'murgaşi' ) );
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( country_id =  'ro' AND name =  'murgaşi' ) );
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'sud-vest' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'sud-vest' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '27' AND me.region_id =  '46' ) );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'dolj' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '27' AND me.region_id =  '17' ) );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '123852' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'pârâul fagului' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '123852',  'siruta',  '123790',  '23',  'siruta',  'ro',  'pârâul fagului',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-est' ) );
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-est' ) );
SELECT me.id, me.name FROM regiontype me WHERE ( name =  'regiune de dezvoltare' );
INSERT INTO region ( country_id, name, region_code, region_code_name, regiontype_id) VALUES (  'ro',  'nord-est',  NULL,  NULL,  '2' ) RETURNING id;
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '32' AND me.region_id =  '47' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '32',  '47' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'neamţ' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'neamţ' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '32' AND me.region_id =  '29' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '32',  '29' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '123843' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'petru vodã' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '123843',  'siruta',  '123790',  '23',  'siruta',  'ro',  'petru vodã',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-est' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-est' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '33' AND me.region_id =  '47' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '33',  '47' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'neamţ' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'neamţ' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '33' AND me.region_id =  '29' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '33',  '29' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '123861' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'poiana largului' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '123861',  'siruta',  '123790',  '23',  'siruta',  'ro',  'poiana largului',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-est' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-est' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '34' AND me.region_id =  '47' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '34',  '47' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'neamţ' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'neamţ' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '34' AND me.region_id =  '29' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '34',  '29' );
COMMIT;
SELECT me.id, me.name, me.country_id, me.city_code, me.city_code_name, me.city_code_sup, me.prefix, me.city_type, me.city_type_system FROM city me WHERE ( ( me.city_code =  '123870' AND me.city_code_name =  'siruta' ) );
SELECT COUNT( * ) FROM city me WHERE ( ( country_id =  'ro' AND name =  'roşeni' ) );
BEGIN WORK;
INSERT INTO city ( city_code, city_code_name, city_code_sup, city_type, city_type_system, country_id, name, prefix) VALUES (  '123870',  'siruta',  '123 790',  '23',  'siruta',  'ro',  'roşeni',  NULL ) RETURNING id;
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-est' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'nord-est' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '35' AND me.region_id =  '47' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '35',  '47' );
COMMIT;
BEGIN WORK;
SELECT COUNT( * ) FROM region me WHERE ( ( country_id =  'ro' AND name =  'neamţ' ) );
SELECT me.id, me.name, me.regiontype_id, me.country_id, me.region_code, me.region_code_name FROM region me WHERE ( ( country_id =  'ro' AND name =  'neamţ' ) );
SELECT me.region_id, me.city_id FROM region_city me WHERE ( ( me.city_id =  '35' AND me.region_id =  '29' ) );
INSERT INTO region_city ( city_id, region_id) VALUES (  '35',  '29' );
COMMIT;
SELECT me.id, me.name, me.parent_id, me.description FROM cms_folder me WHERE ( ( me.description =  'Root folder' AND me.name =  'Root' ) );
INSERT INTO cms_folder ( description, name) VALUES (  'Root folder',  'Root' ) RETURNING id;
INSERT INTO rodauser ( credential_provider) VALUES (  'RODA' ) RETURNING id;
