//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.05 at 02:34:54 AM EEST 
//

package ro.roda.ddi;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

//import elsst.ElsstTerm;

/**
 * <p>
 * Java class for varType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="varType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="location" type="{http://www.icpsr.umich.edu/DDI}locationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="labl" type="{http://www.icpsr.umich.edu/DDI}lablType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="imputation" type="{http://www.icpsr.umich.edu/DDI}imputationType" minOccurs="0"/>
 *         &lt;element name="security" type="{http://www.icpsr.umich.edu/DDI}securityType" minOccurs="0"/>
 *         &lt;element name="embargo" type="{http://www.icpsr.umich.edu/DDI}embargoType" minOccurs="0"/>
 *         &lt;element name="respUnit" type="{http://www.icpsr.umich.edu/DDI}respUnitType" minOccurs="0"/>
 *         &lt;element name="anlysUnit" type="{http://www.icpsr.umich.edu/DDI}anlysUnitType" minOccurs="0"/>
 *         &lt;element name="qstn" type="{http://www.icpsr.umich.edu/DDI}qstnType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="valrng" type="{http://www.icpsr.umich.edu/DDI}valrngType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="invalrng" type="{http://www.icpsr.umich.edu/DDI}invalrngType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="undocCod" type="{http://www.icpsr.umich.edu/DDI}undocCodType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="universe" type="{http://www.icpsr.umich.edu/DDI}universeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TotlResp" type="{http://www.icpsr.umich.edu/DDI}TotlRespType" minOccurs="0"/>
 *         &lt;element name="sumStat" type="{http://www.icpsr.umich.edu/DDI}sumStatType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="txt" type="{http://www.icpsr.umich.edu/DDI}txtType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="stdCatgry" type="{http://www.icpsr.umich.edu/DDI}stdCatgryType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="catgryGrp" type="{http://www.icpsr.umich.edu/DDI}catgryGrpType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="catgry" type="{http://www.icpsr.umich.edu/DDI}catgryType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="codInstr" type="{http://www.icpsr.umich.edu/DDI}codInstrType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="verStmt" type="{http://www.icpsr.umich.edu/DDI}verStmtType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="concept" type="{http://www.icpsr.umich.edu/DDI}conceptType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="derivation" type="{http://www.icpsr.umich.edu/DDI}derivationType" minOccurs="0"/>
 *         &lt;element name="varFormat" type="{http://www.icpsr.umich.edu/DDI}varFormatType" minOccurs="0"/>
 *         &lt;element name="notes" type="{http://www.icpsr.umich.edu/DDI}notesType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="xml-lang" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="source" default="producer">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="archive"/>
 *             &lt;enumeration value="producer"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wgt" default="not-wgt">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="wgt"/>
 *             &lt;enumeration value="not-wgt"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="wgt-var" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="weight" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="qstn" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="files" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="vendor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dcml" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="intrvl" default="discrete">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="contin"/>
 *             &lt;enumeration value="discrete"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="rectype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sdatrefs" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="methrefs" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="pubrefs" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="access" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "varType", propOrder = { "location", "labl", "qstn", "valrng", "invalrng", "universe", "sumStat",
		"txt", "catgry", "verStmt", "varFormat" })
@Entity
// TODO Cosmin Change table name
@Table(schema = "ddi", name = "VariableDDI")
public class VarType {
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@XmlTransient
	private long id_;

	public long getId_() {
		return id_;
	}

	public void setId_(long id_) {
		this.id_ = id_;
	}

	@ManyToOne
	@JoinColumn(name = "VariableDescription_id")
	@XmlTransient
	private DataDscrType datadscrtype;

	public DataDscrType getDatadscrtype() {
		return datadscrtype;
	}

	public void setDatadscrtype(DataDscrType datadscrtype) {
		this.datadscrtype = datadscrtype;
	}

	// @XmlTransient
	// @ManyToMany
	// private List<ElsstTerm> elsstTerm;

	@OneToMany(cascade = { CascadeType.ALL }, mappedBy = "vartype")
	protected List<LocationType> location;

	@OneToMany(cascade = { CascadeType.ALL }, mappedBy = "vartype")
	protected List<LablType> labl;

	@OneToMany(cascade = { CascadeType.ALL }, mappedBy = "vartype")
	protected List<QstnType> qstn;

	@OneToMany(cascade = { CascadeType.ALL }, mappedBy = "vartype")
	protected List<ValrngType> valrng;

	@OneToMany(cascade = { CascadeType.ALL }, mappedBy = "vartype")
	protected List<InvalrngType> invalrng;

	@OneToMany(cascade = { CascadeType.ALL }, mappedBy = "vartype")
	protected List<UniverseType> universe;

	@OneToMany(cascade = { CascadeType.ALL }, mappedBy = "vartype")
	protected List<SumStatType> sumStat;

	@OneToMany(cascade = { CascadeType.ALL }, mappedBy = "vartype")
	protected List<TxtType> txt;

	@OneToMany(cascade = { CascadeType.ALL }, mappedBy = "vartype")
	protected List<CatgryType> catgry;

	@OneToMany(cascade = { CascadeType.ALL }, mappedBy = "vartype")
	protected List<VerStmtType> verStmt;

	@OneToOne(cascade = { CascadeType.ALL })
	protected VarFormatType varFormat;

	@XmlAttribute(name = "ID")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	@XmlSchemaType(name = "ID")
	protected String id;

	// @XmlAttribute(name = "xml-lang")
	// @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	// @XmlSchemaType(name = "NMTOKEN")
	// protected String xmlLang;
	// @XmlAttribute
	// @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	// protected String source;

	@XmlAttribute(required = true)
	protected String name;

	@XmlAttribute
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String wgt;

	// @XmlAttribute(name = "wgt-var")
	// // TODO Cosmin commented IDREF annot.
	// // @XmlIDREF
	// @XmlSchemaType(name = "IDREFS")
	// @ElementCollection
	// protected List<String> wgtVar;
	//
	// @XmlAttribute
	// // TODO Cosmin commented IDREF annot.
	// // @XmlIDREF
	// @XmlSchemaType(name = "IDREFS")
	// @ElementCollection
	// protected List<String> weight;

	// TODO field removed by Cosmin
	// @XmlAttribute(name = "qstn")
	// @XmlIDREF
	// @XmlSchemaType(name = "IDREFS")
	// @ElementCollection
	// protected List<String> qstnAttributeCosmin;

	// TODO Cosmin commented following annotations
	// @XmlIDREF
	// @XmlSchemaType(name = "IDREFS")
	// @ElementCollection
	@XmlAttribute
	protected String files;

	// @XmlAttribute
	// protected String vendor;

	// @XmlAttribute
	// protected String dcml;

	@XmlAttribute
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String intrvl;

	// @XmlAttribute
	// protected String rectype;

	// @XmlAttribute
	// // TODO Cosmin commented IDREF annot.
	// // @XmlIDREF
	// @XmlSchemaType(name = "IDREFS")
	// @ElementCollection
	// protected List<String> sdatrefs;
	// @XmlAttribute
	// // TODO Cosmin commented IDREF annot.
	// // @XmlIDREF
	// @XmlSchemaType(name = "IDREFS")
	// @ElementCollection
	// protected List<String> methrefs;
	// @XmlAttribute
	// // TODO Cosmin commented IDREF annot.
	// // @XmlIDREF
	// @XmlSchemaType(name = "IDREFS")
	// @ElementCollection
	// protected List<String> pubrefs;
	// @XmlAttribute
	// // TODO Cosmin commented IDREF annot.
	// // @XmlIDREF
	// @XmlSchemaType(name = "IDREFS")
	// @ElementCollection
	// protected List<String> access;

	/**
	 * Gets the value of the location property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live List, not a
	 * snapshot. Therefore any modification you make to the returned List will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the location property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getLocation().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the List
	 * {@link LocationType }
	 * 
	 * 
	 */
	public List<LocationType> getLocation() {
		if (location == null) {
			location = new ArrayList<LocationType>();
		}
		return this.location;
	}

	/**
	 * Gets the value of the labl property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live List, not a
	 * snapshot. Therefore any modification you make to the returned List will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the labl property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getLabl().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the List {@link LablType }
	 * 
	 * 
	 */
	public List<LablType> getLabl() {
		if (labl == null) {
			labl = new ArrayList<LablType>();
		}
		return this.labl;
	}

	/**
	 * Gets the value of the qstn property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live List, not a
	 * snapshot. Therefore any modification you make to the returned List will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the qstn property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getQstn().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the List {@link QstnType }
	 * 
	 * 
	 */
	public List<QstnType> getQstn() {
		if (qstn == null) {
			qstn = new ArrayList<QstnType>();
		}
		return this.qstn;
	}

	/**
	 * Gets the value of the valrng property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live List, not a
	 * snapshot. Therefore any modification you make to the returned List will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the valrng property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getValrng().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the List
	 * {@link ValrngType }
	 * 
	 * 
	 */
	public List<ValrngType> getValrng() {
		if (valrng == null) {
			valrng = new ArrayList<ValrngType>();
		}
		return this.valrng;
	}

	/**
	 * Gets the value of the invalrng property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live List, not a
	 * snapshot. Therefore any modification you make to the returned List will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the invalrng property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getInvalrng().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the List
	 * {@link InvalrngType }
	 * 
	 * 
	 */
	public List<InvalrngType> getInvalrng() {
		if (invalrng == null) {
			invalrng = new ArrayList<InvalrngType>();
		}
		return this.invalrng;
	}

	/**
	 * Gets the value of the universe property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live List, not a
	 * snapshot. Therefore any modification you make to the returned List will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the universe property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getUniverse().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the List
	 * {@link UniverseType }
	 * 
	 * 
	 */
	public List<UniverseType> getUniverse() {
		if (universe == null) {
			universe = new ArrayList<UniverseType>();
		}
		return this.universe;
	}

	/**
	 * Gets the value of the sumStat property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live List, not a
	 * snapshot. Therefore any modification you make to the returned List will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the sumStat property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSumStat().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the List
	 * {@link SumStatType }
	 * 
	 * 
	 */
	public List<SumStatType> getSumStat() {
		if (sumStat == null) {
			sumStat = new ArrayList<SumStatType>();
		}
		return this.sumStat;
	}

	/**
	 * Gets the value of the txt property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live List, not a
	 * snapshot. Therefore any modification you make to the returned List will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the txt property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTxt().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the List {@link TxtType }
	 * 
	 * 
	 */
	public List<TxtType> getTxt() {
		if (txt == null) {
			txt = new ArrayList<TxtType>();
		}
		return this.txt;
	}

	/**
	 * Gets the value of the catgry property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live List, not a
	 * snapshot. Therefore any modification you make to the returned List will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the catgry property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCatgry().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the List
	 * {@link CatgryType }
	 * 
	 * 
	 */
	public List<CatgryType> getCatgry() {
		if (catgry == null) {
			catgry = new ArrayList<CatgryType>();
		}
		return this.catgry;
	}

	/**
	 * Gets the value of the verStmt property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live List, not a
	 * snapshot. Therefore any modification you make to the returned List will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the verStmt property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getVerStmt().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the List
	 * {@link VerStmtType }
	 * 
	 * 
	 */
	public List<VerStmtType> getVerStmt() {
		if (verStmt == null) {
			verStmt = new ArrayList<VerStmtType>();
		}
		return this.verStmt;
	}

	/**
	 * Gets the value of the varFormat property.
	 * 
	 * @return possible object is {@link VarFormatType }
	 * 
	 */
	public VarFormatType getVarFormat() {
		return varFormat;
	}

	/**
	 * Sets the value of the varFormat property.
	 * 
	 * @param value
	 *            allowed object is {@link VarFormatType }
	 * 
	 */
	public void setVarFormat(VarFormatType value) {
		this.varFormat = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getID() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setID(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the wgt property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWgt() {
		if (wgt == null) {
			return "not-wgt";
		} else {
			return wgt;
		}
	}

	/**
	 * Sets the value of the wgt property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWgt(String value) {
		this.wgt = value;
	}

	/**
	 * Gets the value of the files property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live List, not a
	 * snapshot. Therefore any modification you make to the returned List will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the files property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFiles().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the List {@link Object }
	 * 
	 * 
	 */
	public String getFiles() {
		return this.files;
	}

	/**
	 * Gets the value of the intrvl property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIntrvl() {
		if (intrvl == null) {
			return "discrete";
		} else {
			return intrvl;
		}
	}

	/**
	 * Sets the value of the intrvl property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIntrvl(String value) {
		this.intrvl = value;
	}

	// public List<ElsstTerm> getElsstTerm() {
	// return elsstTerm;
	// }
	//
	// public void setElsstTerm(List<ElsstTerm> elsstTerm) {
	// this.elsstTerm = elsstTerm;
	// }

}
